version: '3.8'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=correctpassword
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:correctpassword@db:5432/postgres
      - STUB_MODE=false
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: frontend/Dockerfile
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
    name: grafanacopilot_pgdata
